// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVY-6c_yb4WZWNdpfvLRdfvf09rW-KKE',
    appId: '1:270334386672:web:320a1dbc8a99f345c63d35',
    messagingSenderId: '270334386672',
    projectId: 'miguel-marin-trainer',
    authDomain: 'miguel-marin-trainer.firebaseapp.com',
    storageBucket: 'miguel-marin-trainer.appspot.com',
    measurementId: 'G-R3NTFV8R2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAby3RTWNYHjI7VQik0lDRUtQ8BF06JVl8',
    appId: '1:270334386672:android:227e6360071b2b8bc63d35',
    messagingSenderId: '270334386672',
    projectId: 'miguel-marin-trainer',
    storageBucket: 'miguel-marin-trainer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KxHGzJ7Y_QWjh5mGtp_BFtZncIJoz9g',
    appId: '1:270334386672:ios:32093ff14c2bd190c63d35',
    messagingSenderId: '270334386672',
    projectId: 'miguel-marin-trainer',
    storageBucket: 'miguel-marin-trainer.appspot.com',
    iosBundleId: 'com.example.miguelMarinTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KxHGzJ7Y_QWjh5mGtp_BFtZncIJoz9g',
    appId: '1:270334386672:ios:467068ac2528a0edc63d35',
    messagingSenderId: '270334386672',
    projectId: 'miguel-marin-trainer',
    storageBucket: 'miguel-marin-trainer.appspot.com',
    iosBundleId: 'com.example.miguelMarinTraining.RunnerTests',
  );
}
